# Generated by Django 2.0.3 on 2020-02-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='empID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
