# Generated by Django 2.0.3 on 2020-02-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0002_auto_20200223_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='empID',
        ),
    ]
