# Generated by Django 2.0.3 on 2020-03-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0006_auto_20200321_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
