# Generated by Django 2.0.3 on 2020-03-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0007_remove_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuetype',
            name='product',
        ),
    ]
