# Generated by Django 2.0.3 on 2020-03-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0008_remove_issuetype_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='projectName',
            new_name='productName',
        ),
    ]
