# Generated by Django 2.0.3 on 2020-03-21 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0009_auto_20200321_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issueType',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='requestType', to='firstPage.IssueType'),
        ),
        migrations.AddField(
            model_name='issue',
            name='product',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='relatedProduct', to='firstPage.Product'),
        ),
    ]
