# Generated by Django 2.0.3 on 2020-03-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0010_auto_20200321_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
