# Generated by Django 2.0.3 on 2020-03-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0012_auto_20200321_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='closedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
