# Generated by Django 2.0.3 on 2020-03-28 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstPage', '0014_investigationdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueAssignmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('createdDate', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('assignedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignmentAssignedBy', to=settings.AUTH_USER_MODEL)),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignmentAssignedTo', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignmentIssue', to='firstPage.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='IssueUpdateDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('dateAdded', models.DateTimeField(auto_now=True)),
                ('update', models.TextField()),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addedBy', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updateRelatedIssue', to='firstPage.Issue')),
            ],
        ),
    ]
