# Generated by Django 3.0.5 on 2020-04-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0015_issueassignmentdetails_issueupdatedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueupdatedetails',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
