# Generated by Django 3.0.5 on 2020-04-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0017_auto_20200412_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueassignmentdetails',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='documents/Assignment/'),
        ),
        migrations.AlterField(
            model_name='issueupdatedetails',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='documents/Updates/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
